Added guide
sarvesh4396/freeresourceshub pull request #7
Opened 2022-10-04 11:50 UTC by pandeyom331

2022-10-04 14:03 UTC, MuhammadJufri requested changes
And also you forgot to write:
``` npm run startServer ```
Because if you do write that command the user cannot add a new resource

File Name: Installing and deploying guide.txt
On-Line: 6

2022-10-05 02:27 UTC, sarvesh4396 commented
Hey @pandeyom331,
Make a folder named guides
in that make the file INSTALL.md and add guide by taking reference from [here](https://github.com/TryGhost/Ghost#quickstart-install)

2022-10-05 07:21 UTC, MuhammadJufri commented
> Hey @pandeyom331, Make a folder named guides in that make the file INSTALL.md and add guide by taking reference from [here](https://github.com/TryGhost/Ghost#quickstart-install)

Can I make a new pr and fix this issue?

2022-10-05 07:35 UTC, pandeyom331 commented
Is it fine now ?

2022-10-05 08:05 UTC, MuhammadJufri requested changes

2022-10-05 08:05 UTC, MuhammadJufri commented on Guides/Install.md
> +```
You forgot to add ``` npm run startServer ``` to run the server because if you don't run this command the user can't add a new resource

2022-10-05 09:13 UTC, MuhammadJufri approved these changes
Thanks

2022-10-05 14:12 UTC, pandeyom331 commented
pls accept the PR and add relevant tags of hacktoberfest.

2022-10-05 15:00 UTC, sarvesh4396 commented
> pls accept the PR and add relevant tags of hacktoberfest.

Hey @pandeyom331,
Everything looks good to me, just update the link in the readme as the link is redirecting to your repo instead of this repo.

Change https://github.com/pandeyom331/freeresourceshub/blob/master/Guides/Install.md to 
https://github.com/sarvesh4396/freeresourceshub/blob/master/Guides/Install.md

I will merge it soon.

2022-10-05 17:59 UTC, pandeyom331 commented
> > pls accept the PR and add relevant tags of hacktoberfest.
> 
> Hey @pandeyom331, Everything looks good to me, just update the link in the readme as the link is redirecting to your repo instead of this repo.
> 
> Change https://github.com/pandeyom331/freeresourceshub/blob/master/Guides/Install.md to https://github.com/sarvesh4396/freeresourceshub/blob/master/Guides/Install.md
> 
> I will merge it soon.

Done

2022-10-05 19:25 UTC, sarvesh4396 commented
Thank you @pandeyom331

2022-10-05 19:25 UTC, merged